### ISSUE TITLE
Fix JavaTestAzure 

### ISSUE THREAD

**Issue by ugwun** [CJCrafter/ChatGPT-Java-API#21]
Fix AzureOpenAI instance creation in JavaTestAzure. For Azure we also need to define at least `modelName` and `azureBaseUrl`

**Comment by CJCrafter** [comment]
In my review I mentioned this, but I'll also mention it here:

Since these are required arguments, make them required. Changing the order of the parameters is fine since optional parameters are optional.

Alternatively a solution like #19 can be implemented.
