### ISSUE TITLE
Error  “Could not find /.env on the classpath”.

### ISSUE THREAD

**Issue by chen-aq2020** [CJCrafter/ChatGPT-Java-API#24]
I have put ".env" file in the root directory(C:\Users\Administrator\AndroidStudioProjects\[Project name]),but i still get the error  “Could not find /.env on the classpath”.

**Comment by CJCrafter** [comment]
dotenv is just the tool I use for API key, it is completely optional (you can switch out for another tool, if you'd like). 

Since you're working with android studio, I recommend looking at how projects typically store API credentials. 

But without more information, I don't know how to help.

**Comment by chen-aq2020** [comment]
Ok,got it
