### ISSUE TITLE
How to cancel request ?

### ISSUE THREAD

**Issue by renaudcerrato** [CJCrafter/ChatGPT-Java-API#29]
I'm using your API in kotlin's coroutines, but the async API doesn't return any cancellable to cancel the HTTP request. What's the recommended way cancel pending requests?

**Comment by CJCrafter** [comment]
There isn't a native way to do this besides using a future (and using sync on that future instead of async)

If you want a native method added, you should consider opening a PR.

**Comment by CJCrafter** [comment]
I'm going to go ahead and close this since OpenAI doesn't provide a way to stop a request. Either ignore the response or use a future and cancel that (Which is the same as ignoring the response). You waste tokens, unfortunately, but this is the only solution.

**Comment by renaudcerrato** [comment]
Of course, you can cancel an OKHTTP request. The streaming can last several
seconds, and cancelling the request WILL close the socket and cancel the
stream.

Le mer. 6 sept. 2023, 20:19, Collin Barber ***@***.***> a
écrit :

**Comment by renaudcerrato** [comment]
''''
Call call = new OkHttpClient().newCall(your request);
    call.enqueue(new Callback() { // call off UI thread.
        @Override
        public void onFailure(Call call, IOException e) {
            // this is where your call is cancelled: call.isCanceled()
        }

        @Override
        public void onResponse(Call call, Response response) throws IOException {

        }
    });
    call.cancel(); // this is the proper way to cancel an async call.
''''
